media:
  folder: "public/media"  # donde almacenarás imágenes y otros medios

content:
  - name: historia
    label: Historia
    type: collection
    path: "src/content/historia"
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: date
        label: Fecha
        type: date
        required: true
      - name: body
        label: Contenido
        type: rich-text
        required: true

  - name: eventos
    label: Eventos
    type: collection
    path: "src/content/eventos"
    view:
      fields: [ title, date ]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: date
        label: Fecha
        type: date
        required: true
      - name: description
        label: Descripción
        type: rich-text
        required: true

  - name: jugadores
    label: Jugadores
    type: collection
    path: "src/content/jugadores"
    view:
      fields: [ name, position ]
    fields:
      - name: name
        label: Nombre
        type: string
        required: true
      - name: position
        label: Posición
        type: string
        required: true
      - name: bio
        label: Biografía
        type: rich-text
        required: true

  - name: config
    label: Configuración del sitio
    path: "src/config/site-config.yml"
    type: file
    fields:
      - name: title
        label: Título del sitio
        type: string
      - name: description
        label: Descripción del sitio
        type: string
      - name: url
        label: URL del sitio
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Imagen de portada
        type: image
        description: Imagen usada en la previsualización social 
