content:
  - name: "historia"
    label: "Historia"
    folder: "src/content/historia"
    slug: "{{slug}}"
    format: "md"
    fields:
      - type: "string"
        name: "title"
        label: "Título"
        required: true
      - type: "date"
        name: "date"
        label: "Fecha"
        required: true
      - type: "rich-text"
        name: "body"
        label: "Contenido"
        required: true
